### ISSUE TITLE
Board 'Bricked' After firmware update

### ISSUE THREAD

**Issue by zacharthur4223** [bigtreetech/BIGTREETECH-SKR-mini-E3#122]
I was able to compile and load the latest firmware file from this repo, (red LED flashes then stops, file on card changes from .bin to .cur). However, the LCD screen remained blank and the board is now unresponsive. Is there a way to fix this short of replacing the board?

**Comment by thebest07111** [comment]
I have the same issue. It first starts when inserting the usb card but after rebooting it stays blank.

**Comment by bojanpotocnik** [comment]
@bigtreetech can you please update the README with information from e.g. #111 ? There is the same question more than once a week (it is natural that people just do not use search among issues...).

Also, this has been fixed in the upstream Marlin, so @zacharthur4223 and @thebest07111 try to use the latest official Marlin bugfix-2.0.x branch.

**Comment by thebest07111** [comment]
> @bigtreetech can you please update the README with information from e.g. #111 ? There is the same question more than once a week (it is natural that people just do not use search among issues...).
> 
> Also, this has been fixed in the upstream Marlin, so @zacharthur4223 and @thebest07111 try to use the latest official Marlin bugfix-2.0.x branch.

I have read it and it has something to do with platformio build. But I tough that when bigtreetech released a new firmware 10 hours ago it would include that fix?

**Comment by zacharthur4223** [comment]
This was the latest Marlin bug fix as of yesterday 

Zach

**Comment by kramer04** [comment]
so now the bug is fixed ?

**Comment by bojanpotocnik** [comment]
> This was the latest Marlin bug fix as of yesterday

Sorry, this must then be the other issue. 8 days ago, when I last updated [my fork](https://github.com/bojanpotocnik/Marlin) (read the top of the README for changes) the issue was already gone - I think the fix was pushed upstream ~15 days ago.

**Comment by thebest07111** [comment]
Very weird I keep having the same issue even when compiling default marlin firmware with only the btt changes

**Comment by mmende** [comment]
I have the same issue I guess. When I flash the firmware via SD everything works fine until I turn off and on the printer, which leads to a blank screen. I just tried the latest commit in [Marlin bugfix-2.0.x (55595d4)](https://github.com/MarlinFirmware/Marlin/tree/55595d444d6969a7bff58f57959d518059acf31e) with the problem still occurring.

**Comment by thebest07111** [comment]
So basiclly we have a big problem. We cant rollback because it automaticly updates and we cant compile becasue we have a blank screen.

**Comment by bojanpotocnik** [comment]
> until I turn off and on the printer, which leads to a blank screen

@mmende what is the size of your compiled firmware.bin? I shall be less than 224 kB ([ 
Gummibaer's comment](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/issues/47#issuecomment-543390714)).

Can you please try [my fork](https://github.com/bojanpotocnik/Marlin) (default or BLTouch branch) or/and the firmware.bin included my fork, so we can isolate if this is a board, compile or configuration issue? Thanks.

**Comment by mmende** [comment]
It was 233 kB. I just removed SDSUPPORT (brought it down to 216 kB) which seems to fix the problem. Thanks for the tip @bojanpotocnik  Now I will only have to find out what features I can live without.

**Comment by thebest07111** [comment]
What does SDsupport doe can I still use the SD card an usb or not?

**Comment by mmende** [comment]
As far as I know it mainly enables printing from SD card. USB should not be effected by it.

**Comment by thebest07111** [comment]
Oh okay so when you disable I cant print from sd card anymore. That kinda sucks

**Comment by bojanpotocnik** [comment]
In my opinion, when you start using Octoprint you will forgot the SD card feature, so it is fine to disable it. You get slimmer menus (no SD related options in the first screen) and the space for additional features.

**Comment by thebest07111** [comment]
> In my opinion, when you start using Octoprint you will forgot the SD card feature, so it is fine to disable it. You get slimmer menus (no SD related options in the first screen) and the space for additional features.

I know but for some reason whenever I connect my usb cable that has the 5V wire cut my z stepper motor starts whining.

**Comment by cptsoviet** [comment]
Does firmware flashing still work with sdcard disabled?

**Comment by mmende** [comment]
Yes it does

**Comment by brew99** [comment]
If you find that your firmware is larger than 224kB using the env. that BTT indicates in their readme file, just change the env. to STM32F103RC_bigtree_512K and you won't need to worry about any space issues.   This seems to be working for many (including myself)

**Comment by mmende** [comment]
Awesome. Thanks @brew99 ...with STM32F103RC_bigtree_512K as env the larger firmware (with SDSUPPORT) works fine even after rebooting the printer.

**Comment by nmg196** [comment]
So I can't use the firmware.bin precompiled on here? I have to build my own, is that right?  (just trying to understand the solution from the comments above)
